# Generated by Django 5.0.3 on 2026-05-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DashboardMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("total_users", models.IntegerField(default=0)),
                ("active_subscribers", models.IntegerField(default=0)),
                ("growth_rate", models.FloatField(default=0)),
                (
                    "mrr",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("churn_rate", models.FloatField(default=0)),
            ],
            options={
                "verbose_name_plural": "Dashboard Metrics",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="SalesCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("total_sales", models.DecimalField(decimal_places=2, max_digits=15)),
                ("percentage", models.FloatField(default=0)),
                ("color", models.CharField(default="#ec4899", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="UserSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("count", models.IntegerField()),
                ("percentage", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="RevenueTrend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.CharField(max_length=20)),
                ("year", models.IntegerField()),
                ("revenue", models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                "ordering": ["year", "month"],
                "unique_together": {("month", "year")},
            },
        ),
    ]
